library(readr)
coil <- read_delim("coil.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)

CO <- data.frame(coil[c(9:13, 15:19, 21:25)])
variable.names(CO)
SP <- data.frame(CO[1:5])
CR <- data.frame(CO[6:10])
CD <- data.frame(CO[11:15])

library(psych)
fa.parallel(SP)
fa.parallel(CR)
fa.parallel(CD)

library(MVN)
MVN::mvn(CO)

#
# This model specification was automatically generated by Onyx
#
#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- coil ;
model<-"
! regressions 
   CO=~CO__SP*SP
   CO=~CO__CR*CR
   CO=~CO__CD*CD
! residuals, variances and covariances
   SP ~~ VAR_SP*SP
   CR ~~ VAR_CR*CR
   CD ~~ VAR_CD*CD
   CO ~~ 1.0*CO
! observed means
   SP~1;
   CR~1;
   CD~1;
";



result3<-lavaan(model, data=modelData, fixed.x=FALSE, estimator="ML", std.ov=TRUE);
result4<-lavaan(model, data=modelData, fixed.x=FALSE, estimator="MLM", std.ov = TRUE);
lavInspect(result4, what = "theta")

summary(result3, fit.measures=TRUE);
summary(result4, fit.measures=TRUE);

library(semPlot)
semPaths(result4, whatLabels = "std", layout = "tree", color = list(
  lat = rgb(124, 12, 199, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  edge.color = "black",
  edge.label.cex = 1,
  edge.width = 1.5,
  label.cex = 2,
  node.width = 2,
  node.height = 2,
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)

library(semTable)
semTable(list("Model 1" = result3 , "Model 2" = result4),
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Confirmatory Factor Analysis for the Collaboration Scale",
         label = "t3")
