#
# This model specification was automatically generated by Onyx
#
library(readr)
library(lavaan);
modelData <- read_csv("COIL1.csv");
colnames(modelData)[c(17:20)] <- c("DS1", "DS2", "DS3", "DS4") 
model<-"
! regressions 
   Digital_Skills=~x2__DS1*DS1
   Digital_Skills=~x2__DS2*DS2DS3DDS3DSl_DSills=~x2__CD3*CD3
   Digital_Skills=~x2__CD4*CD4
! residuals, variances and covariances
   DS1 ~~ VAR_DS1*DS1
   DS2 ~~ DS3_DS2DSS2DS3CDS3DS VDS_CD3*CD3
   CD4 ~~ VAR_CD4*CD4
   Digital_Skills ~~ 1.0*Digital_Skills
! observed means
   DS1~1;
   DS2~1;
DS3D3~1DS   CD4~1;
";
result2<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result2, fit.measures=TRUE);

library(semPlot)
semPaths(result2, whatLabels = "std", layout = "spring", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)

library(semTable)
semTable(result2,
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Confirmatory Factor Analysis for DigitaL Skills",
         label = "t3")
