library(readr)
coil <- read_delim("coil.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)

#
# This model specification was automatically generated by Onyx
#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- coil ;
model<-"
! regressions 
   Digital_Skills=~x2__Instrumental*IN
   Digital_Skills=~x2__Stra_Privilege*PR
   Digital_Skills=~x2__Stra_Appropriation*AP
   Digital_Skills=~x2__Expansive*EX
! residuals, variances and covariances
   IN ~~ VAR_Instrumental*IN
   PR ~~ VAR_Stra_Privilege*PR
   AP ~~ VAR_Stra_Appropriation*AP
   EX ~~ VAR_Expansive*EX
   Digital_Skills ~~ 1.0*Digital_Skills
! observed means
   IN~1;
   PR~1;
   AP~1;
   EX~1;
";

result1<-lavaan(model, data=modelData, fixed.x=FALSE, estimator="ULS");
result2<-lavaan(model, data=modelData, fixed.x=FALSE, estimator="MLM");
library(boot)
bootstrap_result <- boot(result1, FUN = lav_boot, R = 1000)

summary(result1, fit.measures=TRUE);
summary(result2, fit.measures=TRUE);

library(semPlot)
semPaths(result2, whatLabels = "std", layout = "spring", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)

library(semTable)
semTable(list("Model 1" = result1 , "Model 2" = result2),
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Confirmatory Factor Analysis for the Digital Skill Psychometric Structure",
         label = "t3")
