#
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- read_csv("COIL1.csv");
model<-"
! regressions 
   Digital_Skills=~x2__Instrumental*Instrumental
   Digital_Skills=~x2__Stra_Privilege*Stra_Privilege
   Digital_Skills=~x2__Stra_Appropriation*Stra_Appropriation
   Digital_Skills=~x2__Expansive*Expansive
! residuals, variances and covariances
   Instrumental ~~ VAR_Instrumental*Instrumental
   Stra_Privilege ~~ VAR_Stra_Privilege*Stra_Privilege
   Stra_Appropriation ~~ VAR_Stra_Appropriation*Stra_Appropriation
   Expansive ~~ VAR_Expansive*Expansive
   Digital_Skills ~~ 1.0*Digital_Skills
! observed means
   Instrumental~1;
   Stra_Privilege~1;
   Stra_Appropriation~1;
   Expansive~1;
";
result2<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result2, fit.measures=TRUE);

library(semPlot)
semPaths(result2, whatLabels = "std", layout = "spring", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)

library(semTable)
semTable(result2,
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Statistical Estimated Parameters for the Personality-Leadership Structural Model",
         label = "t3")
