#
# This model specification was automatically generated by Onyx
#
library(readr)
library(lavaan);
modelData <- read_csv("COIL1.csv");
colnames(modelData)[c(17:20)] <- c("CD1", "CD2", "CD3", "CD4") 
model<-"
! regressions 
   Digital_Skills=~x2__CD1*CD1
   Digital_Skills=~x2__CD2*CD2
   Digital_Skills=~x2__CD3*CD3
   Digital_Skills=~x2__CD4*CD4
! residuals, variances and covariances
   CD1 ~~ VAR_CD1*CD1
   CD2 ~~ VAR_CD2*CD2
   CD3 ~~ VAR_CD3*CD3
   CD4 ~~ VAR_CD4*CD4
   Digital_Skills ~~ 1.0*Digital_Skills
! observed means
   CD1~1;
   CD2~1;
   CD3~1;
   CD4~1;
";
result2<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result2, fit.measures=TRUE);

library(semPlot)
semPaths(result2, whatLabels = "std", layout = "spring", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)

library(semTable)
semTable(result2,
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Confirmatory Factor Analysis for Digita Skills",
         label = "t3")
