#
# This model specification was automatically generated by Onyx
library(readr)
library(lavaan);
modelData <- read_csv("COIL1.csv") ;
model<-"
! regressions 
   Collaboration=~Collaboration__Specialization*Specialization
   Collaboration=~Collaboration__Credibility*Credibility
   Collaboration=~Collaboration__Coordination*Coordination
! residuals, variances and covariances
   Specialization ~~ VAR_Specialization*Specialization
   Credibility ~~ VAR_Credibility*Credibility
   Coordination ~~ VAR_Coordination*Coordination
   Collaboration ~~ 1.0*Collaboration
! observed means
   Specialization~1;
   Credibility~1;
   Coordination~1;
";
result1<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(result1, fit.measures=TRUE);

library(semPlot)
semPaths(result1, whatLabels = "std", layout = "tree", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0)

library(semTable)
semTable(result1,
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Statistical Estimated Parameters for the Personality-Leadership Structural Model",
         label = "t3")

