library(readr)
coil <- read_delim("coil.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)
coil <- coil[1:50]
# This model specification was automatically generated by Onyx
#
library(lavaan);
modelData <- coil 
model<-"
! regressions 
   IN=~IN__CompDig1Instr*CompDig1Instr
   IN=~IN__CompDig2Instr*CompDig2Instr
   IN=~IN__CompDig3Instr*CompDig3Instr
   IN=~IN__CompDig4Instr*CompDig4Instr
   IN=~IN__CompDig5Instr*CompDig5Instr
   IN=~IN__CompDig16Instr*CompDig16Instr
   PR=~PR__CompDig6EstratPrivil*CompDig6EstratPrivil
   PR=~PR__CompDig7EstratPrivil*CompDig7EstratPrivil
   PR=~PR__CompDig8EstratPrivil*CompDig8EstratPrivil
   PR=~PR__CompDig9EstratPrivil*CompDig9EstratPrivil
   PR=~PR__CompDig14EstratPrivil*CompDig14EstratPrivil
   PR=~PR__CompDig21EstratPrivil*CompDig21EstratPrivil
   PR=~PR__CompDig22EstratPrivil*CompDig22EstratPrivil
   AP=~AP__CompDig10Estrat3propiac*CompDig10Estrat3propiac
   AP=~AP__CompDig11EstratApropiac*CompDig11EstratApropiac
   AP=~AP__CompDig12Estr3t3propi3c*CompDig12Estr3t3propi3c
   AP=~AP__CompDig13EstratApropiac*CompDig13EstratApropiac
   EX=~EX__CompDig15Exp3nsiv*CompDig15Exp3nsiv
   EX=~EX__CompDig17Expansiv*CompDig17Expansiv
   EX=~EX__CompDig18Expansiv*CompDig18Expansiv
   EX=~EX__CompDig19Expansiv*CompDig19Expansiv
   EX=~EX__CompDig20Exp3nsiv*CompDig20Exp3nsiv
! residuals, variances and covariances
   CompDig1Instr ~~ VAR_CompDig1Instr*CompDig1Instr
   CompDig2Instr ~~ VAR_CompDig2Instr*CompDig2Instr
   CompDig3Instr ~~ VAR_CompDig3Instr*CompDig3Instr
   CompDig4Instr ~~ VAR_CompDig4Instr*CompDig4Instr
   CompDig5Instr ~~ VAR_CompDig5Instr*CompDig5Instr
   CompDig16Instr ~~ VAR_CompDig16Instr*CompDig16Instr
   IN ~~ 1.0*IN
   CompDig6EstratPrivil ~~ VAR_CompDig6EstratPrivil*CompDig6EstratPrivil
   CompDig7EstratPrivil ~~ VAR_CompDig7EstratPrivil*CompDig7EstratPrivil
   CompDig8EstratPrivil ~~ VAR_CompDig8EstratPrivil*CompDig8EstratPrivil
   CompDig9EstratPrivil ~~ VAR_CompDig9EstratPrivil*CompDig9EstratPrivil
   CompDig14EstratPrivil ~~ VAR_CompDig14EstratPrivil*CompDig14EstratPrivil
   CompDig21EstratPrivil ~~ VAR_CompDig21EstratPrivil*CompDig21EstratPrivil
   CompDig22EstratPrivil ~~ VAR_CompDig22EstratPrivil*CompDig22EstratPrivil
   PR ~~ 1.0*PR
   CompDig10Estrat3propiac ~~ VAR_CompDig10Estrat3propiac*CompDig10Estrat3propiac
   CompDig11EstratApropiac ~~ VAR_CompDig11EstratApropiac*CompDig11EstratApropiac
   CompDig12Estr3t3propi3c ~~ VAR_CompDig12Estr3t3propi3c*CompDig12Estr3t3propi3c
   CompDig13EstratApropiac ~~ VAR_CompDig13EstratApropiac*CompDig13EstratApropiac
   AP ~~ 1.0*AP
   CompDig15Exp3nsiv ~~ VAR_CompDig15Exp3nsiv*CompDig15Exp3nsiv
   CompDig17Expansiv ~~ VAR_CompDig17Expansiv*CompDig17Expansiv
   CompDig18Expansiv ~~ VAR_CompDig18Expansiv*CompDig18Expansiv
   CompDig19Expansiv ~~ VAR_CompDig19Expansiv*CompDig19Expansiv
   CompDig20Exp3nsiv ~~ VAR_CompDig20Exp3nsiv*CompDig20Exp3nsiv
   EX ~~ 1.0*EX
   EX ~~ COV_EX_IN*IN
   EX ~~ COV_EX_PR*PR
   EX ~~ COV_EX_AP*AP
   IN ~~ COV_IN_PR*PR
   IN ~~ COV_IN_AP*AP
   AP ~~ COV_AP_PR*PR
! observed means
   CompDig1Instr~1;
   CompDig2Instr~1;
   CompDig3Instr~1;
   CompDig4Instr~1;
   CompDig5Instr~1;
   CompDig16Instr~1;
   CompDig6EstratPrivil~1;
   CompDig7EstratPrivil~1;
   CompDig8EstratPrivil~1;
   CompDig9EstratPrivil~1;
   CompDig14EstratPrivil~1;
   CompDig21EstratPrivil~1;
   CompDig22EstratPrivil~1;
   CompDig10Estrat3propiac~1;
   CompDig11EstratApropiac~1;
   CompDig12Estr3t3propi3c~1;
   CompDig13EstratApropiac~1;
   CompDig15Exp3nsiv~1;
   CompDig17Expansiv~1;
   CompDig18Expansiv~1;
   CompDig19Expansiv~1;
   CompDig20Exp3nsiv~1;
";

result1<-lavaan(model, data=modelData, fixed.x=FALSE, estimator="ML", std.ov=TRUE);
result2<-lavaan(model, data=modelData, fixed.x=FALSE, estimator="MLM", std.ov = TRUE);
# To inspect the standardized estimates for factor loadings
lavInspect(result2, what = "std.all")

lavInspect(result2, what = "std.all")

m1 <- lavInspect(result2, what = "vcov.std.all")
EIGEN <- eigen(m1)
valores <- data.frame(EIGEN$values)
vectores <- EIGEN$vectors

chol(m1)
