#
# This model specification was automatically generated by Onyx
#
library(readr)
library(lavaan);
modelData <- read_csv("COIL1.csv");
model<-"
! regressions 
   Collaboration=~Collaboration__Specialization*Specialization
   Collaboration=~Collaboration__Credibility*Credibility
   Collaboration=~Collaboration__Coordination*Coordination
   Digital_Skills=~Digital_Skills__Stra_Privilege*Stra_Privilege
   Digital_Skills=~Digital_Skills__Instrumental*Instrumental
   Digital_Skills=~Digital_Skills__Stra_Appropriation*Stra_Appropriation
   Digital_Skills=~Digital_Skills__Expansive*Expansive
   Digital_Skills=~Digital_Skills__Collaboration*Collaboration
! residuals, variances and covariances
   Collaboration ~~ 1.0*Collaboration
   Specialization ~~ VAR_Specialization*Specialization
   Credibility ~~ VAR_Credibility*Credibility
   Coordination ~~ VAR_Coordination*Coordination
   Digital_Skills ~~ 1.0*Digital_Skills
   Instrumental ~~ VAR_Instrumental*Instrumental
   Stra_Privilege ~~ VAR_Stra_Privilege*Stra_Privilege
   Stra_Appropriation ~~ VAR_Stra_Appropriation*Stra_Appropriation
   Expansive ~~ VAR_Expansive*Expansive
! observed means
   Specialization~1;
   Credibility~1;
   Coordination~1;
   Instrumental~1;
   Stra_Privilege~1;
   Stra_Appropriation~1;
   Expansive~1;
";
resultT<-lavaan(model, data=modelData, fixed.x=FALSE, missing="FIML");
summary(resultT, fit.measures=TRUE);

resultT2 <- lavaan(model, data=modelData, fixed.x=FALSE, missing="listwise", estimator = "DWLS");
summary(resultT2, fit.measures=TRUE);
summary(resultT, fit.measures=TRUE);

library(semPlo)
semPaths(resultT, whatLabels = "std", layout = "circle", color = list(
  lat = rgb(255, 100, 118, maxColorValue = 255),
  man = rgb(155, 253, 175, maxColorValue = 255)),
  mar = c(10, 5, 10, 5), intercepts = FALSE, residuls = FALSE, nCharNodes = 0,
  shapeMan = "rectangle", shapeLat = "ellipse")

library(semTable)
semTable(list("Model 1" = result3 , "Model 2" = result3b),
         fits = c("chisq", "rmsea", "srmr", "cfi", "tli"),
         columns = c("estsestars", "rsquare" ,"p"),
         paramSets = c("loadings" , "slopes", "latentcovariances"),
         type = "latex", table.float = TRUE , longtable = FALSE,
         caption = "Statistical Estimated Parameters for the Personality-Leadership Structural Model",
         label = "t3")
